# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: MjkyYWU5MWI3NjJmMzVlZWRiYjU1ZmQ3MjE2ZDU5YWI5MjE5ZDg5YmUxMmU2MjMyMGQ0NjMzYWY5MTAxMjlkOGVjMGUyYjIyMWU0ZjJhMmQ2YzJjMGY4YWE3OTMwYTFlMzMwNDYyMzdkNDE1MGFmYTVhYjVkYTI5ZTUwODBhMjE=
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    username: assista-crise
    password:
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    username: assista-crise
    password:
