package com.robin_courault.assista_crise.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AdministrateurAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAdministrateurAllPropertiesEquals(Administrateur expected, Administrateur actual) {
        assertAdministrateurAutoGeneratedPropertiesEquals(expected, actual);
        assertAdministrateurAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAdministrateurAllUpdatablePropertiesEquals(Administrateur expected, Administrateur actual) {
        assertAdministrateurUpdatableFieldsEquals(expected, actual);
        assertAdministrateurUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAdministrateurAutoGeneratedPropertiesEquals(Administrateur expected, Administrateur actual) {
        assertThat(actual)
            .as("Verify Administrateur auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAdministrateurUpdatableFieldsEquals(Administrateur expected, Administrateur actual) {
        // empty method
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAdministrateurUpdatableRelationshipsEquals(Administrateur expected, Administrateur actual) {
        assertThat(actual)
            .as("Verify Administrateur relationships")
            .satisfies(a -> assertThat(a.getUtilisateur()).as("check utilisateur").isEqualTo(expected.getUtilisateur()));
    }
}
