package com.robin_courault.assista_crise.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AnnonceAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAnnonceAllPropertiesEquals(Annonce expected, Annonce actual) {
        assertAnnonceAutoGeneratedPropertiesEquals(expected, actual);
        assertAnnonceAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAnnonceAllUpdatablePropertiesEquals(Annonce expected, Annonce actual) {
        assertAnnonceUpdatableFieldsEquals(expected, actual);
        assertAnnonceUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAnnonceAutoGeneratedPropertiesEquals(Annonce expected, Annonce actual) {
        assertThat(actual)
            .as("Verify Annonce auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAnnonceUpdatableFieldsEquals(Annonce expected, Annonce actual) {
        assertThat(actual)
            .as("Verify Annonce relevant properties")
            .satisfies(a -> assertThat(a.getTitre()).as("check titre").isEqualTo(expected.getTitre()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getCategorie()).as("check categorie").isEqualTo(expected.getCategorie()))
            .satisfies(a -> assertThat(a.getLatitude()).as("check latitude").isEqualTo(expected.getLatitude()))
            .satisfies(a -> assertThat(a.getLongitude()).as("check longitude").isEqualTo(expected.getLongitude()))
            .satisfies(a -> assertThat(a.getAdresse()).as("check adresse").isEqualTo(expected.getAdresse()))
            .satisfies(a -> assertThat(a.getDateCreation()).as("check dateCreation").isEqualTo(expected.getDateCreation()))
            .satisfies(a -> assertThat(a.getDateMaJ()).as("check dateMaJ").isEqualTo(expected.getDateMaJ()))
            .satisfies(a -> assertThat(a.getEtat()).as("check etat").isEqualTo(expected.getEtat()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAnnonceUpdatableRelationshipsEquals(Annonce expected, Annonce actual) {
        // empty method
    }
}
