package com.robin_courault.assista_crise.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AutoriteAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAutoriteAllPropertiesEquals(Autorite expected, Autorite actual) {
        assertAutoriteAutoGeneratedPropertiesEquals(expected, actual);
        assertAutoriteAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAutoriteAllUpdatablePropertiesEquals(Autorite expected, Autorite actual) {
        assertAutoriteUpdatableFieldsEquals(expected, actual);
        assertAutoriteUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAutoriteAutoGeneratedPropertiesEquals(Autorite expected, Autorite actual) {
        assertThat(actual)
            .as("Verify Autorite auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAutoriteUpdatableFieldsEquals(Autorite expected, Autorite actual) {
        assertThat(actual)
            .as("Verify Autorite relevant properties")
            .satisfies(a -> assertThat(a.getNom()).as("check nom").isEqualTo(expected.getNom()))
            .satisfies(a -> assertThat(a.getType()).as("check type").isEqualTo(expected.getType()))
            .satisfies(a -> assertThat(a.getTerritoire()).as("check territoire").isEqualTo(expected.getTerritoire()))
            .satisfies(a -> assertThat(a.getContact()).as("check contact").isEqualTo(expected.getContact()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAutoriteUpdatableRelationshipsEquals(Autorite expected, Autorite actual) {
        // empty method
    }
}
