package com.robin_courault.assista_crise.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CitoyenAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCitoyenAllPropertiesEquals(Citoyen expected, Citoyen actual) {
        assertCitoyenAutoGeneratedPropertiesEquals(expected, actual);
        assertCitoyenAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCitoyenAllUpdatablePropertiesEquals(Citoyen expected, Citoyen actual) {
        assertCitoyenUpdatableFieldsEquals(expected, actual);
        assertCitoyenUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCitoyenAutoGeneratedPropertiesEquals(Citoyen expected, Citoyen actual) {
        assertThat(actual)
            .as("Verify Citoyen auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCitoyenUpdatableFieldsEquals(Citoyen expected, Citoyen actual) {
        // empty method
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCitoyenUpdatableRelationshipsEquals(Citoyen expected, Citoyen actual) {
        assertThat(actual)
            .as("Verify Citoyen relationships")
            .satisfies(a -> assertThat(a.getUtilisateur()).as("check utilisateur").isEqualTo(expected.getUtilisateur()));
    }
}
