package com.robin_courault.assista_crise.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CriseAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCriseAllPropertiesEquals(Crise expected, Crise actual) {
        assertCriseAutoGeneratedPropertiesEquals(expected, actual);
        assertCriseAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCriseAllUpdatablePropertiesEquals(Crise expected, Crise actual) {
        assertCriseUpdatableFieldsEquals(expected, actual);
        assertCriseUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCriseAutoGeneratedPropertiesEquals(Crise expected, Crise actual) {
        assertThat(actual)
            .as("Verify Crise auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCriseUpdatableFieldsEquals(Crise expected, Crise actual) {
        assertThat(actual)
            .as("Verify Crise relevant properties")
            .satisfies(a -> assertThat(a.getTitre()).as("check titre").isEqualTo(expected.getTitre()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getType()).as("check type").isEqualTo(expected.getType()))
            .satisfies(a -> assertThat(a.getDateDebut()).as("check dateDebut").isEqualTo(expected.getDateDebut()))
            .satisfies(a -> assertThat(a.getDateFin()).as("check dateFin").isEqualTo(expected.getDateFin()))
            .satisfies(a -> assertThat(a.getZoneGeographique()).as("check zoneGeographique").isEqualTo(expected.getZoneGeographique()))
            .satisfies(a -> assertThat(a.getCloturee()).as("check cloturee").isEqualTo(expected.getCloturee()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCriseUpdatableRelationshipsEquals(Crise expected, Crise actual) {
        assertThat(actual)
            .as("Verify Crise relationships")
            .satisfies(a -> assertThat(a.getAutorite()).as("check autorite").isEqualTo(expected.getAutorite()));
    }
}
