package com.robin_courault.assista_crise.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ModerationActionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertModerationActionAllPropertiesEquals(ModerationAction expected, ModerationAction actual) {
        assertModerationActionAutoGeneratedPropertiesEquals(expected, actual);
        assertModerationActionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertModerationActionAllUpdatablePropertiesEquals(ModerationAction expected, ModerationAction actual) {
        assertModerationActionUpdatableFieldsEquals(expected, actual);
        assertModerationActionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertModerationActionAutoGeneratedPropertiesEquals(ModerationAction expected, ModerationAction actual) {
        assertThat(actual)
            .as("Verify ModerationAction auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertModerationActionUpdatableFieldsEquals(ModerationAction expected, ModerationAction actual) {
        assertThat(actual)
            .as("Verify ModerationAction relevant properties")
            .satisfies(a -> assertThat(a.getDateAction()).as("check dateAction").isEqualTo(expected.getDateAction()))
            .satisfies(a -> assertThat(a.getMotif()).as("check motif").isEqualTo(expected.getMotif()))
            .satisfies(a -> assertThat(a.getType()).as("check type").isEqualTo(expected.getType()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertModerationActionUpdatableRelationshipsEquals(ModerationAction expected, ModerationAction actual) {
        assertThat(actual)
            .as("Verify ModerationAction relationships")
            .satisfies(a -> assertThat(a.getAdministrateur()).as("check administrateur").isEqualTo(expected.getAdministrateur()))
            .satisfies(a -> assertThat(a.getAnnonce()).as("check annonce").isEqualTo(expected.getAnnonce()))
            .satisfies(a -> assertThat(a.getUtilisateurCible()).as("check utilisateurCible").isEqualTo(expected.getUtilisateurCible()));
    }
}
