package com.robin_courault.assista_crise.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class OffreAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOffreAllPropertiesEquals(Offre expected, Offre actual) {
        assertOffreAutoGeneratedPropertiesEquals(expected, actual);
        assertOffreAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOffreAllUpdatablePropertiesEquals(Offre expected, Offre actual) {
        assertOffreUpdatableFieldsEquals(expected, actual);
        assertOffreUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOffreAutoGeneratedPropertiesEquals(Offre expected, Offre actual) {
        assertThat(actual)
            .as("Verify Offre auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOffreUpdatableFieldsEquals(Offre expected, Offre actual) {
        assertThat(actual)
            .as("Verify Offre relevant properties")
            .satisfies(a -> assertThat(a.getDisponibleDe()).as("check disponibleDe").isEqualTo(expected.getDisponibleDe()))
            .satisfies(a -> assertThat(a.getDisponibleJusqua()).as("check disponibleJusqua").isEqualTo(expected.getDisponibleJusqua()))
            .satisfies(a -> assertThat(a.getQuantite()).as("check quantite").isEqualTo(expected.getQuantite()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOffreUpdatableRelationshipsEquals(Offre expected, Offre actual) {
        assertThat(actual)
            .as("Verify Offre relationships")
            .satisfies(a -> assertThat(a.getAnnonce()).as("check annonce").isEqualTo(expected.getAnnonce()))
            .satisfies(a -> assertThat(a.getCitoyen()).as("check citoyen").isEqualTo(expected.getCitoyen()))
            .satisfies(a -> assertThat(a.getCrise()).as("check crise").isEqualTo(expected.getCrise()))
            .satisfies(a -> assertThat(a.getDemandeses()).as("check demandeses").isEqualTo(expected.getDemandeses()));
    }
}
