package com.robin_courault.assista_crise.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SalonDiscussionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSalonDiscussionAllPropertiesEquals(SalonDiscussion expected, SalonDiscussion actual) {
        assertSalonDiscussionAutoGeneratedPropertiesEquals(expected, actual);
        assertSalonDiscussionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSalonDiscussionAllUpdatablePropertiesEquals(SalonDiscussion expected, SalonDiscussion actual) {
        assertSalonDiscussionUpdatableFieldsEquals(expected, actual);
        assertSalonDiscussionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSalonDiscussionAutoGeneratedPropertiesEquals(SalonDiscussion expected, SalonDiscussion actual) {
        assertThat(actual)
            .as("Verify SalonDiscussion auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSalonDiscussionUpdatableFieldsEquals(SalonDiscussion expected, SalonDiscussion actual) {
        assertThat(actual)
            .as("Verify SalonDiscussion relevant properties")
            .satisfies(a -> assertThat(a.getDateOuverture()).as("check dateOuverture").isEqualTo(expected.getDateOuverture()))
            .satisfies(a -> assertThat(a.getOuvert()).as("check ouvert").isEqualTo(expected.getOuvert()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSalonDiscussionUpdatableRelationshipsEquals(SalonDiscussion expected, SalonDiscussion actual) {
        assertThat(actual)
            .as("Verify SalonDiscussion relationships")
            .satisfies(a -> assertThat(a.getParticipantses()).as("check participantses").isEqualTo(expected.getParticipantses()));
    }
}
