package com.robin_courault.assista_crise.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SinistreAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSinistreAllPropertiesEquals(Sinistre expected, Sinistre actual) {
        assertSinistreAutoGeneratedPropertiesEquals(expected, actual);
        assertSinistreAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSinistreAllUpdatablePropertiesEquals(Sinistre expected, Sinistre actual) {
        assertSinistreUpdatableFieldsEquals(expected, actual);
        assertSinistreUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSinistreAutoGeneratedPropertiesEquals(Sinistre expected, Sinistre actual) {
        assertThat(actual)
            .as("Verify Sinistre auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSinistreUpdatableFieldsEquals(Sinistre expected, Sinistre actual) {
        // empty method
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSinistreUpdatableRelationshipsEquals(Sinistre expected, Sinistre actual) {
        assertThat(actual)
            .as("Verify Sinistre relationships")
            .satisfies(a -> assertThat(a.getUtilisateur()).as("check utilisateur").isEqualTo(expected.getUtilisateur()));
    }
}
